### ISSUE TITLE
Background scrolls when modal is open

### ISSUE THREAD

**Issue by shafi-** [enochndika/kimia-UI#3]
**Describe the bug**
When any modal is open and user tries to scroll, the page in the background scrolls.

**To Reproduce**
1. Go to 'https://kimia-ui.vercel.app/components/modal'
2. Open any modal
3. Scroll up or down'
4. See the background page is scrolling

**Expected behavior**
When modal is open, user should be able to scroll only the modal contents if it has scrollable contents.

**Screenshots**
https://gyazo.com/d5a9336fd65f175f7b9ae8fee9c94f14

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version 90.0.4430.85

**Smartphone (please complete the following information):**
 - Not tested

**Comment by enochndika** [comment]
This is an intended behavior.

If you want to prevent body from scrolling when a modal is opened ,  in the logical part of the component add another useEffect 
```jsx
  useEffect(() => {
    if (isOpen) {
      document.body.style.position = "fixed";
      document.body.style.width = "100%";
    }
  }, [isOpen]);
```

**Comment by shafi-** [comment]
Thank you for the nice work and the reply.
I am not sure - in which case, someone would like to scroll the body while the modal is open. My suggestion would be, to make "prevent body from scrolling when modal open" intended behavior because most of the component providers like Bootstrap/ ant.design etc are doing in that way and that is realistic.
